spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always

  datasource:
    firstdb:
      xa-properties:
        URL: jdbc:h2:mem:first_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
        password:
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      #      xa-data-source-class-name: com.microsoft.sqlserver.jdbc.SQLServerXADataSource # SQLServer ? ?? ???? ???
      #      xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource # MySQL ? ?? ???? ???

      unique-resource-name: 'firstdb'
      min-pool-size: 5
      max-pool-size: 10
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    seconddb:
      xa-properties:
        URL: jdbc:h2:mem:second_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
        password:
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      unique-resource-name: 'seconddb'
      min-pool-size: 5
      max-pool-size: 10
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    thirddb:
      xa-properties:
        URL: jdbc:h2:mem:second_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        user: sa
        password:
      xa-data-source-class-name: org.h2.jdbcx.JdbcDataSource
      unique-resource-name: 'thirddb'
      min-pool-size: 5
      max-pool-size: 10
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy