spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    firstdb:
      url: jdbc:h2:mem:firstdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jpa:
        properties:
          hibernate:
            hbm2ddl.auto: update
            dialect: org.hibernate.dialect.H2Dialect
            show_sql: true
            format_sql: true
            use_sql_comments: true
            jdbc.lob.non_contextual_creation: true
            naming:
              physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    seconddb:
      url: jdbc:h2:mem:seconddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jpa:
        properties:
          hibernate:
            hbm2ddl.auto: update
            dialect: org.hibernate.dialect.H2Dialect
            show_sql: true
            format_sql: true
            use_sql_comments: true
            jdbc.lob.non_contextual_creation: true
            naming:
              physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    thirddb:
      url: jdbc:h2:mem:thirddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      jpa:
        properties:
          hibernate:
            hbm2ddl.auto: update
            dialect: org.hibernate.dialect.H2Dialect
            show_sql: true
            format_sql: true
            use_sql_comments: true
            jdbc.lob.non_contextual_creation: true
            naming:
              physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#    properties:
#      hibernate:
#        hbm2ddl.auto: update
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        jdbc.lob.non_contextual_creation: true